// <auto-generated />
namespace EFWCF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditModuleColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditModuleColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201512300305159_EditModuleColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
