// <auto-generated />
namespace EFWCF.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditModuleSetLen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditModuleSetLen));
        
        string IMigrationMetadata.Id
        {
            get { return "201512231503312_EditModuleSetLen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
